### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by davidanthoff** [ExpandingMan/Arrow.jl#1]
Would be great if you could add an example that just shows how I could access a feather file with this package. I'd very much like to move https://github.com/davidanthoff/FeatherFiles.jl over to use this, and just a simple example would probably help me a lot.

**Comment by ExpandingMan** [comment]
Yes, absolutely!  I'm going to write a full README, I'm not *quite* done with basic features yet.  Tomorrow I hope to have most of the write stuff implemented, and then I'll probably start doing some documentation.

Other than that, one major feature that I'm contemplating is a wrapper around `ArrowVector`s for automatically converting types (right now `ArrowVector`s are very deliberately just pointer wrappers, so they always return the underlying binary type).

I'll definitely let you know explicitly when I think this is in a state where I think it's appropriate for you to rewrite FeatherFiles.jl to use it.  Don't worry, it won't be long.

**Comment by ExpandingMan** [comment]
I haven't forgotten.  Still doing some contemplating of how exactly this will look, so I want to wait to write a README until I think things will be reasonably stable.

I think I've decided that I won't support writing of "lists" (basically arrow arrays of variable length elements such as strings or other arrays) except for basic constructors that do all the writing at once.  One of the difficulties with this package is it's very hard to do anything that ensures any safety for the user because the Arrow standard is so general (for example, it doesn't even specify the size of the buffer you should allocate for the null bit mask).  If I support writing individual elements to lists it will make it too easy for users to make a minor mistake and segfault.  I think inter-process messaging will work fine even if lists are immutable.

**Comment by ExpandingMan** [comment]
Ok, I've finally added some examples!  One of the reasons I spent so long on this is that I needed to figure out if it would be ok to do this entirely without pointers (right now it seems it's just fine).  All the exposed functionality right now should be completely safe.

Take a look at the README.  As I note at the end, I still anticipate there might have to be a few somewhat-significant changes.  I would be super appreciative if you could play with this a little right now and give me your feedback before you dive headfirst into package development.  I don't have a ton of usage examples, so your needs will probably be very instructive to me.

Also, I'm curious what functionality FeatherFiles provides that Feather.jl itself can't, even if FeatherFiles is a specialized interface to Query.jl.  I encourage you to also take a look at the version of Feather.jl I've written using Arrow.jl [here](https://github.com/ExpandingMan/Feather.jl/tree/arrow1).

**Comment by davidanthoff** [comment]
This looks awesome! I have two use-cases in mind: a) I'd like to use this for FeatherFiles.jl and b) it would be super cool to be able to use this to serialize tabular data, send it to a node process and then deserialize it over there with the javascript arrow package.

I won't have the bandwidth to do anything on b) for a while... But for that being able to use the batch/message kind of functionality in the arrow spec would be cool.

I did look at a) in a bit more detail, including at your ``arrow1`` branch in Feather.jl. Here is an idea that would make that kind of integration super, super simple on my end: how about having a FeatherBase.jl package, that provides a ``featherread`` function (similar to the ``csvread`` function in TextParse.jl) that simply returns a tuple, where the first element is a tuple of columns, and the second element a tuple of column names. The tuple of columns would hold subtypes of ``ArrowVector``, i.e. it would essentially just be a view into the memory mapped feather file.

FeatherFiles.jl would then just be the kind of thin wrapper it is today: it would provide the FileIO.jl integration, and it would provide the iterable tables integration. Feather.jl could also depend on FeatherBase.jl and it would provide the DataStreams.jl integration. I generally like a layering where the core data file library packages don't hook into the various data interchange options we have (data streams and iterable tables), but where they can be used stand alone, and then another layer of packages can provide that glue type integration. I've tried to follow that philosophy with the other packages I maintain, e.g. ExcelReader and ExceFiles, ReadStat and StatFiles.

The cool thing about this would be that the combo FeatherFiles/Query would allow a completely streaming data manipulation story, I believe. For example something like ``load("data.feather") |> @filter(_.age>3) |> @map({_.age, _.name}) |> save("result.csv")`` would be completely streaming and at least in theory should easily work with datasets that are larger than main memory.

I have to think about the write story a bit more before I have a clear picture of that.

**Comment by ExpandingMan** [comment]
I think both your "a" and "b" use cases sound very doable with the way I have designed Arrow.jl.  In particular one of my goals was that generally serialization should only require a single line of code (right now literally just `arrowformat(A)`, though it would require various calls `writepadded` to output this in a useful form (those should still be simple as you see in the README).

As far as Feather.jl goes, right now the `Source` and `Sink` objects are basically what you described: they store some metadata (in the form of a tuple of types and a DataStreams `Schema`) and a `Vector` of `ArrowVector` objects which provides an interface to the underlying data itself.  With Arrow.jl the code required for the DataStreams interface within Feather.jl is much more minimal, despite the fact that the two primary objects are the `Source` and `Sink` that satisfy the DataStreams interface.  I *think* Feather.jl would be pretty close to how you are describing FeatherBase.jl: in fact `Feather.read` now does basically what you called `featherread` above would do (if I'm understanding you correctly), albeit perhaps in a slightly different data structure.  Is there something that you feel should absolutely be stripped out of Feather.jl to create FeatherBase.jl?  Right now what's in my `arrow1` branch is pretty minimal even though it satisfies the DataStreams interface.

One thing I've been quite surprised at in this process is that it seems that Arrow doesn't even suggest a standard way for Arrow metadata to be described.  This seems like a big mistake, but perhaps there is some reason I can't see why it would be impossible to have uniform metadata between different formats.  Anyway, this is really the big limitation.  If the metadata were more standard, packages like Feather.jl would only need to be a few lines of code.

**Comment by davidanthoff** [comment]
Mainly I'd like to not depend on Feather.jl and DataStreams.jl in FeatherFiles.jl. Really for three reasons: 1) the whole iterable tables design is essentially an alternative to DataStreams.jl and so layering one over the other seems not ideal, b) DataStreams.jl is tightly coupled with DataFrames.jl and the rest of the ecosystem in terms of version bounds, and I'd like to not have that if possible for the iterable tables ecosystem (for example, I go out of my way to make the iterable tables story work with both the old and the new DataFrames without version bounds), and 3) my sense is that DataStreams.jl is still evolving quite a bit. I might be wrong about the last part, but at least over the last year the churn in DataStreams.jl caused a fair bit of issues on the Query/IterableTables side of things. I'm ok with tracking that for the specific integrations I have, but ideally I'd like a package like FeatherFiles.jl to just be insulated from that. The iterable tables interface is simply in a different stage of its life: it is done and stable, and if at all possible I'd like a package like FeatherFiles.jl to not be integrated with something that seems a little more of a moving target.

Having said that, it would obviously be great to share as much code as possible between the various packages, and so that was the idea for something like FeatherBase.jl or FeatherLib.jl. I should also say that I think that has worked pretty well for the other file IO packages I maintain: because things like ReadStat and ExcelReaders (and TextParse.jl, which I don't maintain but use for CSVFiles.jl) don't have a dependency on the iterable tables ecosystem, they can be used in scenarios where folks don't want to buy into that ecosystem, which I count as a plus.

I'll open another issue about your last paragraph!

**Comment by ExpandingMan** [comment]
Yeah, I definitely hear you about the churn on DataStreams, though I do think that it is pretty stable now.  A while back I started writing a PR for DataStreams with the hope of drastically simplifying it but quickly discovered all the reasons why it is so hard to have a standard like DataStreams.

I definitely need to do more research on IterableTables to understand how it is designed and to what extent is compatible with DataFrames and DataStreams.  I have found that the greatest virtue of DataFrames, especially since Missings, is that the columns are simply `AbstractVector`s and have no requirements other than having an `AbstractVector` interface.  This is very powerful, it allows you to build DataFrames over just about anything, including `ArrowVector`.  Last I looked it had appeared to me that IterableTables had drastically complicated this rather simple and elegant situation which worried me, but certainly I should to return to it to look carefully at it and actually understand what is going on.  These concerns go all the way back to something that I still find very peculiar about tabular data (in my previous life all my data was hierarchical): rows too frequently do not actually make sense as fundamental objects once you actually extract data from a dataframe with the intent of doing something useful.  But that's a long tangent for another discussion...

I hear you about separating base Feather functionality from DataFrames/DataStreams, but I do want to do my part in not fracturing the data ecosystem any further and make sure I really understand IterableTables.  The data ecosystem consisting of two distinct, roughly functionally equivalent, but only partially compatible pieces (DataFrames and IterableTables) doesn't seem like an ideal situation.  Ideally I'd like to do what I can to help them play more nicely together.  Ultimately I'd never want everyone to have to rewrite code for each of these, so if it's definitely necessary I fully support having a FeatherBase or whatever it takes.  I will definitely do my due diligence on this before making a real PR to Feather.

**Comment by davidanthoff** [comment]
The best way to read up on iterable tables is the docs: http://www.david-anthoff.com/IterableTables.jl/latest/developerguide.html, and that section in particular.

> I definitely need to do more research on IterableTables to understand how it is designed and to what extent is compatible with DataFrames and DataStreams.

It fully integrates with ``DataFrame`` and changes absolutely nothing about it. In fact, it makes integration with DataFrames.jl especially simple in these times of churn: it works with the old and the new DataFrame and completely shields packages from that transition. For packages like StatPlots.jl and all the other packages that have iterable tables integration (https://github.com/davidanthoff/IterableTables.jl) the whole transition to ``Missings`` on the DataFrame.jl side was a non-event. They just work with the old and the new version of DataFrames.jl at the same time, not a single line of code adjustment needed on their end.

I have connectors for DataStreams.jl as well. They are slightly less smooth, but it should mostly work.

> Last I looked it had appeared to me that IterableTables had drastically complicated this rather simple and elegant situation

That is incorrect. IterableTables changes nothing about that.

> rows too frequently do not actually make sense as fundamental objects once you actually extract data from a dataframe with the intent of doing something useful.

YES, that is a very good point! Iterable tables is fundamentally row based. But, it now lives in TableTraits.jl, and I've been thinking a lot about additional interfaces that can complement it and are more column oriented, and still work in the Query.jl world. It is not a simple problem, but I'm slowly converging on something... The way I see the iterable tables interface in this story is that it is the least common denominator. It is the simplest, most basic way to interop. That has really panned out, if you look at the list of sinks and sources for iterable tables, it is LONG, and it is long because iterating rows is simple and flexible and doesn't involve much work, so it was relatively easy to integrate it with many sinks and sources.

>  but I do want to do my part in not fracturing the data ecosystem any further and make sure I really understand IterableTables. The data ecosystem consisting of two distinct, roughly functionally equivalent, but only partially compatible pieces (DataFrames and IterableTables) doesn't seem like an ideal situation.

I also don't want a fractured ecosystem, trust me! The comparison DataFrames / IterableTables makes no sense, though. One is a table implementation, the other one an interface, they play very different roles and are really complements, not alternatives. Describing them as functionally equivalent is incorrect.

**Comment by ExpandingMan** [comment]
Well, first of all, I was confusing your IterableTables with [IndexedTables](https://github.com/JuliaComputing/IndexedTables.jl), so what I said in my last post was actually referring to IndexedTables!  So yeah, if I said some things that made no sense, that's why!

**Comment by davidanthoff** [comment]
Hehe, no worries, even I mix up the two names from time to time, they are just too similar :)
