### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by davidanthoff** [ExpandingMan/Arrow.jl#26]
I believe you now tagged a version, but I don't see anything in METADATA.jl, right?

Did you enable https://github.com/attobot/attobot? You first need to enable that, and then create the release here in the repo. If you didn't enable attobot so far, you can enable it, then delete the release (but not the tag) and then recreate the release right away. That should automatically create a PR in METADATA.jl.

**Comment by ExpandingMan** [comment]
Sorry, I tagged and then started registering the other night, but I had some sort of problem and just haven't gotten to it yet.  If you are feeling anxious about it, it would be perfectly fine with me if you made the METADATA commit yourself.  Otherwise, I'll get to this as soon as I can.  I may do a v0.1.1 very quickly, so I think that will do the attobot auto thing as well.

**Comment by ExpandingMan** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/14022

**Comment by ExpandingMan** [comment]
Merged!
