### ISSUE TITLE
WeakRefString

### ISSUE THREAD

**Issue by davidanthoff** [ExpandingMan/Arrow.jl#5]
Are they still used? Or not? I always get nervous when I see them, but I didn't fully understood how they are used here.

**Comment by davidanthoff** [comment]
Is the following interpretation right: if I read a buffer, and I use a ``List{String}``, it will not ever use ``WeakRefString`` in any way? I.e. if I index into the ``List{String}``, I'll just get normal ``String`` objects, that of course at that point are being allocated?

**Comment by ExpandingMan** [comment]
Yes, `List{String}` will never use `WeakRefString` in any way.  Originally I had planned to give the option to also do `List{WeakRefString}` but I'm not sure I'll still support that since I moved everything away from pointers.  I need to do one more very careful pass to make certain that there is nothing left that is unsafe that is not explicitly labeled as such, but I'm pretty sure right now everything I expose is completely safe.

**Comment by ExpandingMan** [comment]
I have completely removed all references to `WeakRefString`.
